version: "3"

networks:
  alif_tech_test:
    driver: bridge
volumes:
  mysql:

services:
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx_alif
    restart: unless-stopped
    volumes:
      - ../:/application
      - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - alif_tech_test

  php_fpm:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    container_name: php_fpm_alif
    working_dir: /application
    restart: unless-stopped
    volumes:
      - ../:/application
    networks:
      - alif_tech_test

  mysql:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_alif
    volumes:
      - mysql:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "alif"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "alif"
    networks:
      - alif_tech_test